apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-deployment
  labels:
    app: json-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
      - name: json-server
        image: chaimahs/json-server:v1 # Remplacez par le nom de votre image Docker
        ports:
        - containerPort: 3000
        command: ["npx", "json-server", "--watch", "/app/db.json", "--host", "0.0.0.0"]
