apiVersion: v1
kind: Service
metadata:
  name: json-server-service
spec:
  selector:
    app: json-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort # Utilisez ClusterIP si vous testez localement